version: "3.8"

services:
  test:
    build:
      context: ./test
      dockerfile: Dockerfile
    container_name: test
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  test-account:
    build:
      context: ./test-account
      dockerfile: Dockerfile
    container_name: test-account
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - test
